CREATE SCHEMA SA AUTHORIZATION DBA;

-- 个人
CREATE TABLE person(
  id   bigint NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
  name VARCHAR(45) DEFAULT NULL
);

-- 插入测试数据
INSERT INTO person (name) VALUES ('name-test-1');